### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by wwhurley** [forumone/gesso-theme-libsass-drupal7#6]
Why are the actual theme files one level deep into the folder? It ends up being a little awkward being `public/sites/all/themes/gesso/gesso`

**Comment by coreylafferty** [comment]
This repo is just meant as a shortcut to get Gesso with Libsass working in our starter kit setup, so I kept the tasks outside of the theme folder so they're easy to integrate into our projects. Once we move the tasks into the theme itself, this structure won't be needed.
